packages:
  - apps/*
  - packages/*
  - playground/*

catalog:
  vite-plugin-singlefile: ^2.3.3

catalogMode: prefer

catalogs:
  cli:
    bumpp: "^11.1.0"
  types:
    "@types/node": ^24
    typescript: ^7.0.2
    miniprogram-api-typings: 5.2.1
  parser:
    ultrahtml: ^1.6.0
  vue:
    "@vue/compiler-vapor": 3.6.0-rc.1
    "@vue/reactivity": 3.6.0-rc.1
    "@vue/runtime-dom": 3.6.0-rc.1
    "@vue/runtime-vapor": 3.6.0-rc.1
    "@vue/runtime-core": 3.6.0-rc.1
    "@vue/shared": 3.6.0-rc.1
    "@vitejs/plugin-vue": ^6.0.7
    "vue": 3.6.0-rc.1

  test:
    jsdom: "^25.0.0"

  vite:
    vite: npm:@voidzero-dev/vite-plus-core@0.2.5
    vite-plus: 0.2.5

  webview:
    "@webviewjs/webview": 0.3.2

overrides:
  vite: "catalog:vite"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
